### ISSUE TITLE
Editable input for Time of Interest (TOI)

### ISSUE THREAD

**Issue by vskorole** [EOX-A/QgsWcsClient2#17]
In the current version of plugin is impossible to edit datetime in the input box for TOI in the DescribeEOCoverageSet tab. You can only change it by scrolling digits in the hardcoded format. We need format for our datetime which follow yyyy-mm-ddThh:mm:ssZ but you use format without seconds. Can you extend format or make possible to edit input box?

**Comment by eox-cs1** [comment]
Hi vskorole,

I'll have a look at it, but give me a couple of days.

**Comment by eox-cs1** [comment]
Hi vskorole,
I checked the time fields and they are actually editable. Not only by scrolling but also by by typing. Unfortunately its not the whole field at once, but each item separately i.e. YYYY  or MM etc. can be edited or scrolled, as you mentioned. I don't know why this is but I couldn't find a way to configure it differently.
Regarding the seconds - I don't understand your real need so it is difficult for me to test it thoroughly. But I assume you will have a distinct use-case for it, and so I prepared a specific GUI just for you. 
Since I cant fully test it I would like to ask you  if you can do that and provide me feedback if it works as you would expect it. For the time being I will not release this as a new version to the QGis Repo so I attach it here and you need to unpack it and copy it into your qgis-plugin directory (in linux this is /home/xxxx/.qgis2/python/plugins/QgsWcsClient2)
[ui_qgswcsclient2.py.zip](https://github.com/EOX-A/QgsWcsClient2/files/2428378/ui_qgswcsclient2.py.zip)

Please let me know if this works for you, and maybe you can shortly describe me your use-case. I will then release it to the QGis Repo.
ciao

**Comment by vskorole** [comment]
Hi Christian,
Here is what I get from server when make a request
{
    "errors": [
        "temporal start datetime is invalid: [2011-01-01T00:00Z] is not a valid datetime : Invalid format: \"2011-01-01T00:00Z\" is malformed at \"Z\".",
        "temporal end datetime is invalid: [2017-01-01T23:00Z] is not a valid datetime : Invalid format: \"2017-01-01T23:00Z\" is malformed at \"Z\"."
    ]
}

With your new interface it works fine.
Hope you will include it in the new release.
Thank you.


Slav Korolev
Work :  301-851-8339
Cell:      240-481-4003
Slav.korolev@nasa.gov<mailto:Slav.korolev@nasa.gov>
Vyacheslav.s.korolev@raytheon.com
